all:				Node.class ActualNode.class Main.class FileUtil.class CoordinatorTimer.class


ActualNode.class:		ActualNode.java
				@javac ActualNode.java

CoordinatorTimer.class:		CoordinatorTimer.java
				@javac CoordinatorTimer.java

Node.class:		Node.java
				@javac Node.java

FileUtil.class:		FileUtil.java
				@javac FileUtil.java

Main.class:		Main.java
				@javac Main.java

clean:
				@rm -rf *.class *~